[package]
name = "api_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio"] }
serde = { version = "1.0.219", features = ["derive"] }
