[package]
name = "sqlite_test"
version = "0.1.0"
edition = "2024"

[dependencies]
bcrypt = "0.17.0"
serde = { version = "1.0.219", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio-native-tls"] }
tokio = { version = "1.45.0", features = ["full"] }
